#!/usr/bin/env python3

from socket import socket, AF_UNIX, SOCK_DGRAM
from gi.repository import GObject
import subprocess
import sys

sock = socket(AF_UNIX, SOCK_DGRAM)
try:
    sock.connect('/tmp/ricochet')
except FileNotFoundError:
    print("Could not connect to Ricochet process; make sure it is running.")
    sys.exit()

#TODO: handle ConnectionRefusedError or remove named pipe on main program close.

# have to encode str to bytes in python3
s = bytes(sys.argv[1], 'UTF-8')
sock.sendall(s)
