#!/usr/bin/env python3

# Ricochet: A different angle on music.
# Copyright (C) 2013-2014 Pearce Dedmon

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


from gi.repository import Gst, Gtk, GObject, Notify, Gio, GLib
import os

from lib.browser import Browser
from lib import settings
from lib.control import Control
from lib.signals import Server

VERSION = '0.3.5'
print('Ricochet v%s' % VERSION)

settings = settings.get_settings()

if settings['backend'] == "gstreamer":
    from lib import gstream as backend
    Gst.init()
elif settings['backend'] == "mpd":
    from lib import mpdbind as backend
else:
    print("Invalid backend: should be 'mpd' or 'gstreamer'")


class Ricochet(Gtk.Application):

    def __init__(self):
        Gtk.Application.__init__(self,
                                 application_id="apps.judgedreads.ricochet",
                                 flags=Gio.ApplicationFlags.FLAGS_NONE)
        GLib.set_application_name('Ricochet')
        GLib.set_prgname('Ricochet')
        self.connect("activate", self.on_activate)

    def on_key_press(self, widget, event, player):
        if event.hardware_keycode == 65:
            player.toggle()

    def on_activate(self, app):
        window = Gtk.ApplicationWindow()
        window.set_border_width(0)
        window.set_icon_from_file("/opt/ricochet/images/ricochet.png")
        window.set_default_size(1000, 700)

        Notify.init('Ricochet')

        player = backend.Player(settings)
        music = settings['music_dir']

        browser = Browser(player)
        for artist in sorted(os.listdir(music)):
            for album in os.listdir(os.path.join(music, artist)):
                browser.add_album(os.path.join(artist, album))

        server = Server(player)
        server.main()
        control = Control(player, server)

        hbox = Gtk.Box()
        hbox.pack_start(control, False, False, 0)
        hbox.pack_start(browser, True, True, 0)
        browser.flowbox.get_child_at_index(0).grab_focus()

        window.add(hbox)
        window.connect("key-press-event", self.on_key_press, player)
        app.add_window(window)
        window.show_all()

if __name__ == "__main__":
    app = Ricochet()
    app.run(None)
    # TODO: need a shutdown method to properly close the gstreamer
    # pipeline.
