#!/bin/bash

directory=$( pwd | awk -F / '{ print $NF}' )

if [ "$directory" == "ricochet" ]; then
    if [ "$1" == "install" ]; then
        echo "Create program directory: /opt/ricochet"
        mkdir /opt/ricochet
        echo "Copying program files"
        cp -r -p lib /opt/ricochet
        cp -r -p images /opt/ricochet
        cp misc/ricochet.desktop /usr/share/applications/
        cp ricochet /opt/ricochet/
        mkdir -p /home/"$(logname)"/.config/ricochet
        cp -p misc/ricochetrc /home/"$(logname)"/.config/ricochet/
        ln -s /opt/ricochet/ricochet /usr/bin/ricochet
        echo "Done"
    elif [ "$1" == "remove" ]; then
        echo "Removing program files"
        rm -r /opt/ricochet
        rm /usr/share/applications/ricochet.desktop
        rm -r /home/"$(logname)"/.config/ricochet
        rm /usr/bin/ricochet
        echo "Done"
    else
        echo "Usage:"
        echo "  ./setup install"
        echo "or:"
        echo "  ./setup remove"
        echo "To upgrade: use './setup remove' then './setup install'."
    fi
else
    echo "This script must be run in the main directory: 'ricochet'."
fi
